parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     kcb_vereinsheim
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       smtp.sinfin.de
    mailer_user:       dummy@sinfin.de
    mailer_password:   dummy

    locale:            de
    secret:            dasfajrnf4h5ibafirbfsdf
