jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Kcb\Bundle\VereinsheimBundle\Entity\Mitglied: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_ALLOWED_TO_SWITCH]

    providers:
        mitglieder:
            entity:
                class: Kcb\Bundle\VereinsheimBundle\Entity\Mitglied
                property: email

    firewalls:
        main:
            pattern:    ^/
            anonymous:
            form_login: ~
            logout: ~
            remember_me:
                key: %secret%
                lifetime: 31536000

    access_control:
        - { path: ^/profil/activate/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil/, roles: ROLE_MITGLIED }
        - { path: ^/anwesende/toggle, roles: ROLE_MITGLIED }
        - { path: ^/mitglieder/, roles: ROLE_ADMIN }
