jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Kcb\Bundle\VereinsheimBundle\Entity\Mitglied: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_MITGLIED, ROLE_ALLOWED_TO_SWITCH]

    providers:
        mitglieder:
            entity:
                class: Kcb\Bundle\VereinsheimBundle\Entity\Mitglied
                property: email

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:
            form_login: ~
            logout: ~

    access_control:
#        - { path: ^/anwesende, roles: ROLE_MITGLIED }
#        - { path: ^/mitglieder, roles: ROLE_ADMIN }
