<?php

namespace Kcb\Bundle\VereinsheimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnwesenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnwesenderRepository extends EntityRepository
{
}
